# Generated by Django 4.2.5 on 2023-10-04 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('description', models.CharField(max_length=10000, null=True)),
                ('price', models.CharField(max_length=1000, null=True)),
                ('Tquantity', models.CharField(max_length=1000, null=True)),
                ('directions', models.CharField(max_length=1000, null=True)),
                ('side_effects', models.CharField(max_length=1000, null=True)),
                ('warnings', models.CharField(max_length=1000, null=True)),
                ('consume_type', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
