# Generated by Django 4.2.5 on 2023-10-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.cart'),
        ),
    ]
