# Generated by Django 4.2.5 on 2023-10-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_remove_assign_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='price',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='assign',
            name='req_qnty',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
