# Generated by Django 4.2.5 on 2023-10-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedbacks',
        ),
    ]
